name: "Action composite"
description: "A test action"
inputs:
  username:
    required: true
    description: "a username in a bottle"

runs:
  using: composite
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: echo "${{ github.action_path }}"
      shell: bash
    - name: Read the username
      shell: bash
      run: |
        echo "hello ${{ inputs.username }}"
        message_in_the_bottle="secret message"
