name: A workflow for build
on: workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: SET CURRENT_BRANCH
        run: |
             $branchName = "${{github.ref}}".Split("/")["${{github.ref}}".Split("/").Length -1]
        id: set-current-branch
      # print branch name
      - name: Get branch name
        run: echo 'The branch name is' ${{ steps.set-current-branch.outputs.branchName }}
