name: A workflow for build
on: 
  workflow_dispatch:
    inputs:
      SEMVER:
        description: 'Semantic Version (in format Major.Minor.Patch)'
        required: true

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Set current branch
        id: set-current-branch
        run: |
             $branchName = "${{github.ref}}".Split("/")["${{github.ref}}".Split("/").Length -1]
             echo "::set-output name=CURRENT_BRANCH::$(echo $branchName)"
             echo "Running on $branchName "
             #Linux version: echo "##[set-output name=CURRENT_BRANCH;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Get current branch
        run: |
             echo "Current branch is ${{ steps.set-current-branch.outputs.CURRENT_BRANCH }} "

      - name: Build
        run: |
             echo "Executing build"
             echo "hello artifact ${{ github.event.inputs.SEMVER }}" > myartifact.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
            name: myartifact_${{ steps.set-current-branch.outputs.CURRENT_BRANCH }}_${{ github.event.inputs.SEMVER }}
            path: myartifact.txt
