name: A workflow for build
on: workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Set current branch
        id: set-current-branch
        run: |
             $branchName = "${{github.ref}}".Split("/")["${{github.ref}}".Split("/").Length -1]
             echo "::set-output name=CURRENT_BRANCH::$(echo $branchName)"
             echo "Running on $branchName "
             #Linux version: echo "##[set-output name=CURRENT_BRANCH;]$(echo ${GITHUB_REF#refs/heads/})"
              Get-Date -Format o
              
      - name: Get current branch
        run: | 
             echo "Current branch is ${{ steps.set-current-branch.outputs.CURRENT_BRANCH }} "
             Get-Date -Format o
      
      - name: Build
        run: | 
             echo "Executing build"
             Get-Date -Format o
             
      - name: Upload artifact
        run: |
             echo "Upload artifact"
             Get-Date -Format o

