name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  example_job:
    name: Pass input
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: |
          echo "hello ${{ inputs.username }}"
