name: Call a reusable workflow

on:
  workflow_dispatch:
    inputs:
      username:
        required: true


jobs:
  call-workflow-passing-data:
    uses: martcus/devops-in-actions/.github/workflows/reusable.yml@master
    with:
      username: ${{ inputs.username }}
