on:
  workflow_dispatch

name: check uppercase
jobs:
  set-var:
    runs-on: ubuntu-latest
    outputs:
      artifact: ${{ steps.current-artifact.outputs.CURRENT_ARTIFACT }}
    steps:
      - name: Set variable
        id: set-variable
        shell: bash
        run: |
              echo "::set-output name=MY_VAR::$(echo ${{ secrets.MY_TESTING_SECRET }})"
          
  update-ghpages:
    runs-on: ubuntu-latest
    needs: set-var
    name: Check
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: master
          path: master
      - name: Check if github pages must be update    
        run: |
          cd ./master
          GREP=$(grep '[A-Z]' README.md > greppone || true)
          if [ ! -s greppone ]; then
            echo "No uppercase characters detected"
            exit 0
          else
            echo "Uppercase characters detected!" 
            exit 1
          fi
      - name: check secrets
        run: |
          pwd
          cd ./master/scripts
          ls -al
          chmod +x ./hello.sh
          bash -x ./hello.sh ${{ secrets.MY_TESTING_SECRET }}
          bash -x ./hello.sh ${{needs.set-var.outputs.MY_VAR}}
          
          
