name: Checkout cache

on:
  workflow_dispatch:

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - run: |
          myfile=checkout.cache2.txt
          echo "Hello World!?!" >> $myfile
          git add $myfile
          git config --local user.email "github-actions@users.noreply.github.com"
          git config --local user.name "github-actions"
          git commit -m "updated $myfile"
          git push

  deploy:
    needs: update-version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0
    # https://github.com/actions/checkout/issues/439
    - name: workaround
      run: git pull origin master
    - name: cat publish file
      run: |
        # the changes made in job1 are not reflected here
         cat checkout.cache.txt
