name: Default-environment-variables

on:
  workflow_dispatch:

jobs:
  variables:
    runs-on: ubuntu-latest
    steps:
      # source: https://www.ntweekly.com/2021/07/23/print-single-or-all-environment-variables-with-github-actions/
      - name: Print all environment variables
        run: |
          env
      # source: https://dev.to/mihinduranasinghe/working-with-environment-variables-github-actions-part-2-46po
      - name: echo-default-env-variables
        run: |
            #GITHUB_WORKFLOW The name of the workflow.
            #GITHUB_RUN_ID A unique number for each run within a repository. This number does not change if you re-run the workflow run.
            #GITHUB_RUN_NUMBER A unique number for each run of a particular workflow in a repository. This number begins at 1 for the workflow's first run, and increments with each new run. This number does not change if you re-run the workflow run.
            #GITHUB_ACTION The unique identifier (id) of the action.
            #GITHUB_ACTIONS Always set to true when GitHub Actions is running the workflow. You can use this variable to differentiate when tests are being run locally or by GitHub Actions.
            #GITHUB_ACTOR The name of the person or app that initiated the workflow.
            #GITHUB_EVENT_NAME The name of the webhook event that triggered the workflow.
            #GITHUB_REPOSITORY The owner and repository name.
            #GITHUB_EVENT_PATH The path of the file with the complete webhook event payload.
            #GITHUB_WORKSPACE The GitHub workspace directory path.
            #GITHUB_SHA The commit SHA that triggered the workflow.
            #GITHUB_REF The branch or tag ref that triggered the workflow.
            #GITHUB_HEAD_REF Only set for forked repositories. The branch of the head repository.
            #GITHUB_BASE_REF Only set for forked repositories. The branch of the base repository.
            #GITHUB_SERVER_URL Returns the URL of the GitHub server.
            #GITHUB_API_URL Returns the API URL.
            #GITHUB_GRAPHQL_URL Returns the GraphQL API URL.

            echo "Home: ${HOME}"
            echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
            echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
            echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
            echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
            echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
            echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
            echo "GITHUB_SHA: ${GITHUB_SHA}"
            echo "GITHUB_REF: ${GITHUB_REF}"

  context:
    runs-on: ubuntu-latest
    steps:
      # source: https://docs.github.com/en/actions/learn-github-actions/contexts
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
