name: A workflow for deploy
on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
      semver:
        description: 'Semantic Version (in format Major.Minor.Patch)'
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: windows-latest
    steps:
      - name: Set current artifact name
        id: current-artifact
        run: |
             echo "::set-output name=CURRENT_ARTIFACT::$(echo myartifact_${{ github.event.inputs.branch }}_${{ github.event.inputs.semver }})"
   
      - name: Retrieve artifact list
        id: artifact-list
        run: |
             # echo "::set-output name=ARTIFACT_LIST::$(curl -fs https://api.github.com/repos/${{github.repository}}/actions/artifacts)"
             (Invoke-WebRequest -Uri https://api.github.com/repos/${{github.repository}}/actions/artifacts).Content > artifact-list-file.json
             
      - name: Get latest artifact id
        id: max_id
        run: |
             $myid = cat artifact-list-file.json | jq '[ .artifacts[] | select(.name == \"${{ steps.current-artifact.outputs.CURRENT_ARTIFACT }}\" and .expired == false) | .id ] | max' 
             echo "::set-output name=MAX_ID::$myid"
      
      - name: Get lastest artifact url
        id: url
        run: |
             $myurl = cat artifact-list-file.json | jq '.artifacts[] | select( .id == ${{ steps.max_id.outputs.MAX_ID }} ) | .archive_download_url'
             echo "::set-output name=URL::$myurl"
             
      - name: Download artifact
        id: download
        run: |
             # $Header = @{"Authorization" = "Basic"+[System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes(username[:{ ${{ secrets.ACTIONS_TOKEN }} }]))}
             # Invoke-RestMethod -Method GET -Header $Header -ContentType "application/json" -SkipCertificateCheck -uri "${{ steps.url.outputs.URL }}"
             
             curl -i -u martcus${{ secrets.ACTIONS_TOKEN }} "${{ steps.url.outputs.URL }}"
             cat "${{ steps.current-artifact.outputs.CURRENT_ARTIFACT }}"
             
      - name: Call script for deploy/rollback
        run: |
            echo "Call script ${{ steps.download.conclusion }}"

      - name: Echo Variables
        if: ${{ always() }}
        run: |
             echo "${{ steps.current-artifact.outputs.CURRENT_ARTIFACT }}"
             echo "${{ steps.max_id.outputs.MAX_ID }}"
             echo "${{ steps.url.outputs.URL }}"
