name: A workflow for deploy
on: 
  workflow_dispatch:
    inputs:
      semver:
        description: 'Semantic Version (in format Major.Minor.Patch)'
        required: true
      branch:
        description: 'Branch name'
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: windows-latest
    steps:
      - name: Set current artifact name
        id: current-artifact
        run: |
             echo "::set-output name=CURRENT_ARTIFACT::$(echo myartifact_${{ github.event.inputs.branch }}_${{ github.event.inputs.semver }})"
   
      - name: Retrieve artifact list
        id: artifact-list
        run: |
             # echo "::set-output name=ARTIFACT_LIST::$(curl -fs https://api.github.com/repos/${{github.repository}}/actions/artifacts)"
             (Invoke-WebRequest -Uri https://api.github.com/repos/${{github.repository}}/actions/artifacts).Content > artifact-list-file.json
             cat artifact-list-file.json
             
      - name: Get latest artifact id 
        id: maxId
        run: |
             $myid = cat artifact-list-file.json | jq '[ .artifacts[] | select(.name == "${{ steps.current-artifact.outputs.CURRENT_ARTIFACT }}" and .expired == false) | .id ] | max' 
             echo ::set-output name=MAX_ID::$( $myid )
      
     # - name: Get lastest artifact url
     #   id: url
     #   run: echo ::set-output name=URL::$( ${{ steps.artifact-list.outputs.ARTIFACT_LIST }} |
     #       jq '.artifacts[] | select(.name == "${{ steps.current-artifact.outputs.CURRENT_ARTIFACT }}" and .id == ${{ steps.maxId.outputs.MAX_ID }} ) | .archive_download_url')
      
      - run: echo "${{ steps.maxId.outputs.maxId }}"
      - run: echo "${{ steps.url.outputs.URL }}"
      - run: echo "URL=${{ steps.url.outputs.URL }}" >> ${{ env.URL }}
      - run: echo "${{ env.URL }}"
