name: Dynamic Runner
on:
  workflow_dispatch:
    inputs:
      destinationEnv:
        type: choice
        description: 'Name of deploy destination Environment'
        options: 
        - DEV
        - TEST
        - UAT
        required: true

jobs:
  check-runner:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.runner.outputs.runner }}
    steps:
    - id: runner
      run: |
        if [ "${{ github.event.inputs.destinationEnv }}" = "DEV" ]; then
          echo "::set-output name=runner::ubuntu-latest"
        elif [ "${{ github.event.inputs.destinationEnv }}" = "TEST" ]; then
          echo "::set-output name=runner::macos-latest"
        elif [ "${{ github.event.inputs.destinationEnv }}" = "UAT" ]; then
          echo "::set-output name=runner::windows-latest"
        fi

  test:
    needs: [check-runner]
    runs-on: ${{ needs.check-runner.outputs.runner }}
    steps:
      - run: echo I Ran
