name: Ubuntu - Try checkout external repo
on: workflow_dispatch

jobs:
  externalrepo:
    name: External repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0
        with:
          repository: martcus/log4sh
          ref: master
      - name: Try the magic script
        run: |
          chmod +x ./script/log4.sh
          chmod +x ./test/test.sh
          ./test/test.sh
