name: Kubectl env

on:
  workflow_dispatch:

jobs:
  script:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: "latest"
      id: install
