name: Kubectl env

on:
  workflow_dispatch:

jobs:
  kube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - name: Setup Kubectl
        uses: azure/setup-kubectl@v3.2
        with:
          version: "latest"
        id: install
  
      - name: Adding markdown
        run: echo '### Hello world! :rocket:' >> $GITHUB_STEP_SUMMARY
      
      - run: kubectl version 
