name: matrix include

on:
  workflow_dispatch:

jobs:
  frontned:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
  
  backend:
    strategy:
      matrix:
        include:
          - backend: backend
            node: 16
            npm: 6
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - if: ${{ matrix.npm }}
        run: npm install -g npm@${{ matrix.npm }}
      - run: npm --version
