name: OpenVPN

on:
  workflow_dispatch:

jobs:
  openvpn:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.3.0
      
      - name: Install OpenVPN
        run: |
          sudo apt-get update
          sudo apt-get --assume-yes --no-install-recommends install openvpn          

      - name: Run OpenVPN
        run: openvpn --version
