name: Pull Request on develop
on: 
  pull_request:
    branches:
      - develop
    types: [closed]

jobs:
  builddeploy:
    if: github.event.pull_request.merged == true
    name: Build and Deploy on develop
    runs-on: ubuntu-latest
    steps:
      - run: |
             echo "Hello World!"
