name: Summary

on:
  workflow_dispatch:

jobs:
  summary:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          echo "- step 1a" >> summary.txt
          echo "- step 2a" >> summary.txt
      - name: Step 2
        run: |
          echo "- step 2" >> summary.txt
      - run: |
          cat summary.txt >> $GITHUB_STEP_SUMMARY
