name: Summary

on:
  workflow_dispatch:

jobs:
  summary:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          echo "| component | status |" >> summary.txt
          echo "| --- | --- |" >> summary.txt
          echo "| Component 1 | 🟢 |" >> summary.txt
          echo "| Component 2 | 🟢 |" >> summary.txt
      - name: Step 2
        run: |
          echo "| Component 2 | 🔴 |" >> summary.txt
      - run: |
          cat summary.txt >> $GITHUB_STEP_SUMMARY
