name: Summary

on:
  workflow_dispatch:

jobs:
  summary:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          echo "- step 1a\n" >> summary.txt
          echo "- step 2a\n" >> summary.txt
      - name: Step 2
        run: |
          echo "- step 2\n" >> summary.txt
      - run: |
          cat summary.txt >> $GITHUB_STEP_SUMMARY
