name: Summary

on:
  workflow_dispatch:

jobs:
  summary:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "- step 1" >> $GITHUB_STEP_SUMMARY
        run: echo "- step 2" >> $GITHUB_STEP_SUMMARY
      - name: Step 2
        run: echo "- step 2" >> $GITHUB_STEP_SUMMARY
