name: Summary

on:
  workflow_dispatch:

jobs:
  summary:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          STEP1_SUMMARY+="- step 1a\n"
          STEP1_SUMMARY+="- step 1b\n"

          # echo "$STEP1_SUMMARY" >> $GITHUB_STEP_SUMMARY
      - name: Step 2
        run: |
          STEP2_SUMMARY+="- step 1b\n"

          # echo "$STEP2_SUMMARY" >> $GITHUB_STEP_SUMMARY
      - run: |
          echo "$STEP1_SUMMARY" >> $GITHUB_STEP_SUMMARY
          echo "$STEP2_SUMMARY" >> $GITHUB_STEP_SUMMARY
