name: Summary

on:
  workflow_dispatch:

jobs:
  summary:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          echo "- step 1a" >> $CUSTOM_STEP_SUMMARY
          echo "- step 1b" >> $CUSTOM_STEP_SUMMARY
      - name: Step 2
        run: echo "- step 2" >> $CUSTOM_STEP_SUMMARY
      - name: Summary
        run: |
          echo "$CUSTOM_STEP_SUMMARY" >> $GITHUB_STEP_SUMMARY
